name: Peter J. Sucy Digital Arts
favicon: null
layout_spectrum: 0.88265
typography_spectrum: 1
title: Photography by Peter J. Sucy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#837f80'
    - '#404040'
    - '#e3c541'
  brandStrength: 0.8125
  lightness: 0.2547186319716275
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
