name: Peter J. Sucy Digital Arts
favicon: null
layout_spectrum: 0.9848236371763051
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e2e1df'
    - '#bab4b4'
    - '#8a807e'
    - '#6b533d'
    - '#201509'
  brandStrength: 0.6842350123915821
  lightness: 0.2547186319716275
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
